spring:
  cloud:
    consul:
      enabled: true
      host: 127.0.0.1
      port: 8500
      discovery:
        healthCheckPath: /health
        healthCheckInterval: 15s
        instanceId: serivce-consul
  application:
    name: serivce-consul
server:
  port: 8502